DROP TABLE IF EXISTS rooms;
CREATE TABLE rooms (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(28) NOT NULL,
    description VARCHAR(255)
);
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    room_id INT UNSIGNED NOT NULL,
    nick VARCHAR(24) NOT NULL,
    posting VARCHAR(1000) NOT NULL,
    date DATETIME NOT NULL,
    ip VARCHAR(39) NOT NULL
);
DROP TABLE IF EXISTS bans;
CREATE TABLE bans (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(39) NOT NULL,
    reason VARCHAR(100) NOT NULL
);
DROP TABLE IF EXISTS reports;
CREATE TABLE reports (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    post_id INT UNSIGNED NOT NULL,
    reason VARCHAR(100) NOT NULL,
    reporter_ip VARCHAR(39) NOT NULL
);
DROP TABLE IF EXISTS mods;
CREATE TABLE mods (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usern VARCHAR(24) NOT NULL,
    passw VARCHAR(128) NOT NULL,
    ip VARCHAR(39) NOT NULL,
    last_login DATETIME NOT NULL,
    rank INT(1) NOT NULL
);